name: LaCarotte.Web Docker Publish

on:
  push:
    paths:
      - 'frontend/web/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd frontend/web/
          docker build -t ${{ github.repository_owner }}/lacarotte-web:latest .

      - name: Push Docker image
        run: |
          cd frontend/web/
          docker push ghcr.io/${{ github.repository_owner }}/lacarotte-web:latest
